name: Deploy

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
    	branches: [master]

    workflow_dispatch:

jobs:
    deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Deploy package to digitalocean
              uses: appleboy/ssh-action@master

              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: 22
                  script: ./bin/update-infosec-app.sh
